### PR TITLE
Pep8ize

### PR DESCRIPTION
**Pull request by rob-baron**
This is everything for the python within troposphere

### CODE REVIEW

**Review by xuhang57 — APPROVED** [review]
LGTM. However, CI checks have failed. You will see more details when you clicks the `Details`

**Review by xuhang57 — CHANGES_REQUESTED** [review]
CI fails

**Comment by rob-baron** [comment]
Yes, I can see that CI was failing.  I was trying to get CI to accept multiple languages - it seems like something that travis ci should be able to do.  Doing some research on the we indicates that travis ci does not support multiple languages within one build, so for now, the work-a-round is to check the python in one build and check the javascript in another.

**Comment by xuhang57** [comment]
I can see that you can see the CI was failing. How about using Travis for javascript only? Since there is not so much code in python here.

**Comment by rob-baron** [comment]
Backed out the changes to the travis file.  

Travis does not seem to be able to deal with 2 different languages in the same project.  Now CI will fail due to lint in javascript which is being fixed in a separate PR.

**Review by xuhang57 — APPROVED** [review]

**Review by knikolla — APPROVED** [review]

**Pull request merged**
