### PR TITLE
Remove intercom

### PR DESCRIPTION
**Pull request by xuhang57**
easy fix.

### CODE REVIEW

**Review by kamfonik — APPROVED** [review]
Looks pretty straightforward, assuming it passes CI.

**Comment by kamfonik** [comment]
I guess those settings should either default to NONE or you should make sure they are never checked anywhere else, otherwise you might get KeyError or similar.

**Comment by xuhang57** [comment]
@kamfonik  Thanks Laura for reminding me of this. I sent another patch and removed the Intercom in the setting files.

**Comment by kamfonik** [comment]
+1 to the new changes, again assuming CI passes

**Review by rob-baron — APPROVED** [review]
ok.  Hopefully this is the last we see of Intercom.

**Pull request merged**
